# Generated by Django 4.2.7 on 2023-12-05 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.TextField(default='none', max_length=100)),
                ('event_venue', models.TextField(default='none', max_length=100)),
                ('event_city', models.TextField(default='none', max_length=100)),
                ('event_state', models.TextField(default='none', max_length=100)),
                ('event_date', models.TextField(default='none', max_length=100)),
                ('event_image', models.TextField(default='none', max_length=100)),
                ('event_url', models.TextField(default='none', max_length=100)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
